---
title: "Dissolved Organic Carbon and Dissolved Total Nitrogen"
author: "Joe Futrelle, Kate Morkeski"
date: "2024-06-03"
output:
  html_document:
    df_print: paged
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
library(dplyr)
library(tidyr)
library(readr)

```

Read data table

```{r}
# data file is downloaded and _input appended to filename to allow for column modifications
# v3: from Taylor to allow for some manual corrections. v2: from submodule
data_table <- read_csv(here("nes-lter-doc-transect_input.csv"), na = c("nan", "NaN", "")) # v1, v3
#data_table <- read_csv(here("nes-lter-doc-transect_input.csv")) #v2

```
Adjust columns to match metadata

```{r}

# # used in v2 for data from python submodule
# data_table <- data_table |> 
#   relocate(date_analyzed, .after = distance_km) |>
#   relocate(filename, .after = date_analyzed) |>
#   rename(date_time_utc = date) |>
#   rename(station_distance = distance_km) |> 
#   replace_na(list(cast = NaN, niskin = NaN, latitude = NaN, longitude = NaN, depth = NaN, doc = NaN, dtn = NaN, distance_km = NaN)) |>
#   replace_na(list(replicate = ""))

# used in v3 for data not from python submodule:
data_table <- data_table |> 
  rename(date_time_utc = date) |>
  select(-temperature, -salinity, -comments) |>
  replace_na(list(replicate = "")) |>
  rename(iode_quality_flag_c = quality_flag_c) |>
  rename(iode_quality_flag_n = quality_flag_n) 
data_table$date_time_utc <- as.POSIXlt(data_table$date_time_utc, format = "%m/%d/%Y %H:%M", TZ ="UTC")
data_table$date_analyzed <- as.POSIXlt(data_table$date_analyzed, format = "%m/%d/%Y %H:%M", TZ ="UTC")
data_table$date_analyzed <- as.Date(data_table$date_analyzed)

write.csv(data_table, "nes-lter-doc-transect.csv", na = "NaN", row.names = FALSE)

```


Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}

data_table <- read_csv(here("nes-lter-doc-transect.csv"))
excel_to_template(here("nes-lter-doc-transect-info"), "nes-lter-doc-transect", rights="CC0", data_table=data_table, file_type=".md")
```
Generate the package and insert the parent project node into the resulting EML

```{r}
pkg_id <- "knb-lter-nes.23.3"

make_eml(here(),
         dataset.title="Dissolved Organic Carbon (DOC) and Dissolved Total Nitrogen (DTN) from Northeast U.S. Shelf Long Term Ecological Research (NES-LTER) Transect cruises, ongoing since 2022",
         data.table="nes-lter-doc-transect.csv",
         data.table.description="DOC and DTN from discrete water column samples on NES-LTER cruises",
         data.table.name = "nes-lter-doc-transect",
         temporal.coverage = temporal_coverage(data_table$date_time_utc),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(data_table$latitude, data_table$longitude),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id, "parent_project_NESI-II.txt")
```
